#ifndef _ERROR_RTP_H_
#define _ERROR_RTP_H_

typedef enum {
    LRTP_SUCC=0,

    PARAMETER_ERROR=100,

    //INTERNAL_ERROR=200,
    SOCKET_CREATE_FAILED=200,
    SOCKET_BIND_FAILED,
    SOCKET_ADDR_PORT_ERROR,
    SOCKET_ADDR_FLAG_ERROR,
    SOCKET_SEND_FAILED,
    SOCKET_RECV_FAILED,

    //BAD_PACKET=300,
    BP_VERSION=300,
    BP_NO_SSRC,
    BP_TOO_SHORT,
    BP_OTHERS,

    OTHER_ERRORS=400,

} RTP_ERROR;

#endif
